GET http://localhost:8000/cars/


###
GET http://localhost:8000/retrieve-cars-with-model/


###
GET http://localhost:8000/retrieve-cars-with-prefetch-related/


###
GET http://localhost:8000/api/cars/


###
GET http://localhost:8000/api/cars-2/


###
GET http://localhost:8000/api/cars-3/